import type {
  BasicBlockDefinition,
  Bot,
  BotState,
  PortType,
  Room,
  StrategyNodeData,
} from './types';

export const portShapeLabel: Record<PortType, string> = {
  Universe: '이중 원',
  Asset: '원형',
  AssetPair: '쌍점 원',
  PriceSeries: '선 정사각형',
  VolumeSeries: '막대 정사각형',
  Scalar: '마름모',
  BooleanSignal: '삼각형',
  ScoreVector: '쌍점 마름모',
  WeightVector: '선 마름모',
  PositionState: '선 육각형',
  OrderIntent: '육각형',
  ApprovedOrder: '확인 육각형',
  EventTrigger: '점 삼각형',
  Metric: '이중 마름모',
};

export const basicLibrary: BasicBlockDefinition[] = [
  {
    id: 'asset',
    order: 0,
    stage: '1 · 유니버스',
    title: '원하는 종목 선택하기',
    description: '사용할 종목 집합을 사용자가 직접 만듭니다.',
    color: '#0F766E',
    output: { id: 'universe', label: '종목 집합', type: 'Universe' },
    parameters: [{ key: 'symbols', label: '회사명 또는 심볼', type: 'text', placeholder: '직접 입력', required: true, primary: true }],
  },
  {
    id: 'price',
    order: 1,
    stage: '2 · 시장 데이터',
    title: '가격 데이터 불러오기',
    description: '선택한 종목의 확정된 가격 데이터를 연결합니다.',
    color: '#0369A1',
    input: { id: 'universe', label: '종목 집합', type: 'Universe' },
    output: { id: 'price', label: '가격 시계열', type: 'PriceSeries', timeframe: '5m' },
    parameters: [{
      key: 'timeframe',
      label: '시간축',
      type: 'select',
      required: true,
      primary: true,
      options: [{ label: '1분', value: '1m' }, { label: '5분', value: '5m' }, { label: '일봉', value: '1d' }],
    }],
  },
  {
    id: 'indicator',
    order: 2,
    stage: '3 · 특징·지표',
    title: '지표 계산하기',
    description: '가격을 비교 가능한 수치로 변환합니다.',
    color: '#6D28D9',
    input: { id: 'price', label: '가격 시계열', type: 'PriceSeries', timeframe: '5m' },
    output: { id: 'scalar', label: '계산 결과', type: 'Scalar' },
    parameters: [
      {
        key: 'method',
        label: '계산 방식',
        type: 'select',
        required: true,
        primary: true,
        options: [{ label: '단순 이동평균', value: 'sma' }, { label: '지수 이동평균', value: 'ema' }, { label: '가격 변화율', value: 'roc' }],
      },
      { key: 'period', label: '계산 기간', type: 'number', placeholder: '직접 입력', required: true, min: 2, max: 250 },
    ],
  },
  {
    id: 'condition',
    order: 3,
    stage: '4 · 시작 신호',
    title: '시작 조건 만들기',
    description: '수치 비교 결과를 참·거짓 신호로 만듭니다.',
    color: '#C2410C',
    input: { id: 'scalar', label: '계산 결과', type: 'Scalar' },
    output: { id: 'signal', label: '시작 신호', type: 'BooleanSignal' },
    parameters: [
      {
        key: 'operator',
        label: '비교',
        type: 'select',
        required: true,
        primary: true,
        options: [{ label: '보다 큼', value: 'gt' }, { label: '보다 작음', value: 'lt' }, { label: '위로 돌파', value: 'cross-up' }, { label: '아래로 돌파', value: 'cross-down' }],
      },
      { key: 'threshold', label: '기준값', type: 'number', placeholder: '직접 입력', required: true },
    ],
  },
  {
    id: 'exit',
    order: 4,
    stage: '5 · 종료 신호',
    title: '끝나는 조건 만들기',
    description: '시작한 전략을 끝낼 조건을 별도로 정합니다.',
    color: '#C2410C',
    input: { id: 'entry-signal', label: '시작 신호', type: 'BooleanSignal' },
    output: { id: 'exit-signal', label: '완성된 신호', type: 'BooleanSignal' },
    parameters: [{ key: 'exitRule', label: '종료 조건', type: 'text', placeholder: '직접 입력', required: true, primary: true }],
  },
  {
    id: 'portfolio',
    order: 5,
    stage: '6 · 포트폴리오',
    title: '목표 비중 정하기',
    description: '신호가 발생했을 때 사용할 목표 비중을 정합니다.',
    color: '#15803D',
    input: { id: 'signal', label: '완성된 신호', type: 'BooleanSignal' },
    output: { id: 'weights', label: '목표 비중', type: 'WeightVector' },
    parameters: [{ key: 'allocation', label: '목표 비중', type: 'number', suffix: '%', placeholder: '직접 입력', required: true, primary: true, min: 0, max: 100 }],
  },
  {
    id: 'risk',
    order: 6,
    stage: '7 · 위험관리',
    title: '위험 규칙 적용하기',
    description: '목표 비중을 사용자가 정한 위험 한도로 제한합니다.',
    color: '#B91C1C',
    input: { id: 'weights', label: '목표 비중', type: 'WeightVector' },
    output: { id: 'approved', label: '승인된 주문', type: 'ApprovedOrder' },
    parameters: [{ key: 'maxWeight', label: '종목당 최대 비중', type: 'number', suffix: '%', placeholder: '직접 입력', required: true, primary: true, min: 0, max: 100 }],
  },
  {
    id: 'order',
    order: 7,
    stage: '8 · 주문 실행',
    title: '모의 주문 만들기',
    description: '위험 검사를 통과한 주문만 모의체결 큐로 보냅니다.',
    color: '#1F2937',
    input: { id: 'approved', label: '승인된 주문', type: 'ApprovedOrder' },
    output: { id: 'order-event', label: '주문 이벤트', type: 'OrderIntent', observation: true },
    parameters: [{
      key: 'orderType',
      label: '주문 방식',
      type: 'select',
      required: true,
      primary: true,
      options: [{ label: '시장가 모의주문', value: 'market' }, { label: '지정가 모의주문', value: 'limit' }],
    }],
  },
  {
    id: 'record',
    order: 8,
    stage: '9 · 관찰·기록',
    title: '판단 기록 남기기',
    description: '전략 실행에는 영향을 주지 않고 판단 근거만 기록합니다.',
    color: '#0E7490',
    input: { id: 'order-event', label: '주문 이벤트', type: 'OrderIntent', observation: true },
    parameters: [{
      key: 'record',
      label: '기록 범위',
      type: 'select',
      required: true,
      primary: true,
      options: [{ label: '입력값과 판단 근거', value: 'reason' }, { label: '상태 변화만', value: 'changes' }],
    }],
  },
];

const node = (definition: StrategyNodeData): StrategyNodeData => definition;

export const proLibrary: StrategyNodeData[] = [
  node({
    blockId: 'direct-universe',
    label: '직접 선택 바스켓',
    stage: '유니버스',
    detail: '사용자 입력 종목 집합',
    description: '회사명이나 심볼을 직접 입력해 전략이 읽을 종목 집합을 만듭니다. 서비스가 종목을 추천하거나 자동으로 채우지 않습니다.',
    color: '#0F766E',
    icon: 'grid',
    inputs: [],
    outputs: [{ id: 'universe', label: '종목 집합', type: 'Universe' }],
    parameterSchema: [{ key: 'symbols', label: '종목', type: 'text', placeholder: '직접 입력', required: true, primary: true }],
    parameters: { symbols: '' },
    dataCapability: 'reference_data',
  }),
  node({
    blockId: 'price-bars',
    label: '가격·거래량',
    stage: '시장 데이터',
    detail: '확정된 봉 데이터',
    description: '서버가 확정한 가격과 거래량만 전달합니다. 시간축은 포트 타입 일부이므로 다른 시간축과 직접 연결할 수 없습니다.',
    color: '#0369A1',
    icon: 'wave',
    inputs: [{ id: 'universe', label: '종목 집합', type: 'Universe' }],
    outputs: [
      { id: 'price', label: '가격', type: 'PriceSeries', timeframe: '5m' },
      { id: 'volume', label: '거래량', type: 'VolumeSeries', timeframe: '5m' },
    ],
    parameterSchema: [
      { key: 'timeframe', label: '시간축', type: 'select', required: true, primary: true, options: [{ label: '1분', value: '1m' }, { label: '5분', value: '5m' }, { label: '일봉', value: '1d' }] },
      { key: 'freshness', label: '최대 지연', type: 'number', suffix: '초', required: true, primary: true, min: 1, max: 120 },
    ],
    parameters: { timeframe: '5m', freshness: '' },
    dataCapability: 'intraday_5m',
  }),
  node({
    blockId: 'resample',
    label: '시간축 리샘플',
    stage: '시장 데이터',
    detail: '명시적 시간축 변환',
    description: '분봉을 일봉처럼 다른 시간축으로 바꿀 때 집계 방식과 타임존을 명시합니다.',
    color: '#0369A1',
    icon: 'wave',
    inputs: [{ id: 'price-in', label: '원본 가격', type: 'PriceSeries', timeframe: '5m' }],
    outputs: [{ id: 'price-out', label: '변환 가격', type: 'PriceSeries', timeframe: '1d' }],
    parameterSchema: [
      { key: 'target', label: '변환 시간축', type: 'select', required: true, primary: true, options: [{ label: '5분', value: '5m' }, { label: '일봉', value: '1d' }] },
      { key: 'timezone', label: '타임존', type: 'select', required: true, options: [{ label: '거래소 시간', value: 'exchange' }, { label: 'KST', value: 'kst' }] },
    ],
    parameters: { target: '1d', timezone: 'exchange' },
  }),
  node({
    blockId: 'moving-average',
    label: '이동평균',
    stage: '특징·지표',
    detail: '가격을 수치로 변환',
    description: '선택한 기간의 가격을 단순 또는 지수 방식으로 평균해 하나의 수치 시계열을 만듭니다.',
    color: '#6D28D9',
    icon: 'function',
    inputs: [{ id: 'price', label: '가격 시계열', type: 'PriceSeries', timeframe: '5m' }],
    outputs: [{ id: 'scalar', label: '평균값', type: 'Scalar' }],
    parameterSchema: [
      { key: 'method', label: '방식', type: 'select', required: true, primary: true, options: [{ label: 'SMA', value: 'sma' }, { label: 'EMA', value: 'ema' }] },
      { key: 'period', label: '기간', type: 'number', required: true, primary: true, min: 2, max: 250 },
    ],
    parameters: { method: 'sma', period: '' },
    formula: 'MAₜ = Σ Price / N',
    dataCapability: 'intraday_5m',
  }),
  node({
    blockId: 'condition',
    label: '조건 비교',
    stage: '조건·신호',
    detail: '수치에서 참·거짓 생성',
    description: '수치 입력을 사용자가 정한 연산자와 기준값으로 비교해 Boolean 신호를 만듭니다.',
    color: '#C2410C',
    icon: 'bolt',
    inputs: [{ id: 'scalar', label: '수치', type: 'Scalar' }],
    outputs: [{ id: 'signal', label: '조건 신호', type: 'BooleanSignal' }],
    parameterSchema: [
      { key: 'operator', label: '연산자', type: 'select', required: true, primary: true, options: [{ label: '보다 큼', value: 'gt' }, { label: '보다 작음', value: 'lt' }, { label: '위로 돌파', value: 'cross-up' }, { label: '아래로 돌파', value: 'cross-down' }] },
      { key: 'threshold', label: '기준값', type: 'number', required: true, primary: true },
    ],
    parameters: { operator: 'gt', threshold: '' },
    formula: 'Signal = Scalar operator threshold',
  }),
  node({
    blockId: 'and-logic',
    label: '모두 충족 AND',
    stage: '일정·제어',
    detail: '두 신호를 하나로 결합',
    description: '입력된 모든 Boolean 신호가 참일 때만 다음 단계로 참을 전달합니다.',
    color: '#A16207',
    icon: 'clock',
    inputs: [
      { id: 'signal-a', label: '신호 A', type: 'BooleanSignal' },
      { id: 'signal-b', label: '신호 B', type: 'BooleanSignal' },
    ],
    outputs: [{ id: 'signal', label: '결합 신호', type: 'BooleanSignal' }],
    parameterSchema: [],
    parameters: {},
    formula: 'A ∧ B',
  }),
  node({
    blockId: 'target-weight',
    label: '목표 비중',
    stage: '포트폴리오',
    detail: '신호를 목표 비중으로 변환',
    description: '신호가 참일 때 사용할 자산 비중을 만듭니다. 비중 수치는 사용자가 직접 입력합니다.',
    color: '#15803D',
    icon: 'pie',
    inputs: [{ id: 'signal', label: '조건 신호', type: 'BooleanSignal' }],
    outputs: [{ id: 'weights', label: '목표 비중', type: 'WeightVector' }],
    parameterSchema: [
      { key: 'allocation', label: '총 비중', type: 'number', suffix: '%', required: true, primary: true, min: 0, max: 100 },
      { key: 'cash', label: '최소 현금', type: 'number', suffix: '%', required: true, min: 0, max: 100 },
    ],
    parameters: { allocation: '', cash: '' },
  }),
  node({
    blockId: 'risk-guard',
    label: '비중·손실 제한',
    stage: '위험관리',
    detail: '주문 전 위험 검사',
    description: '목표 비중과 손실 범위를 검사합니다. 위험 블록은 직렬로 적용되고 하나라도 거부하면 주문이 실행되지 않습니다.',
    color: '#B91C1C',
    icon: 'shield',
    inputs: [{ id: 'weights', label: '목표 비중', type: 'WeightVector' }],
    outputs: [{ id: 'approved', label: '승인 주문', type: 'ApprovedOrder' }],
    parameterSchema: [
      { key: 'maxWeight', label: '종목당 최대', type: 'number', suffix: '%', required: true, primary: true, min: 0, max: 100 },
      { key: 'dailyLoss', label: '하루 최대 손실', type: 'number', suffix: '%', required: true, primary: true, min: 0, max: 100 },
    ],
    parameters: { maxWeight: '', dailyLoss: '' },
  }),
  node({
    blockId: 'paper-order',
    label: '모의 주문 실행',
    stage: '주문 실행',
    detail: '승인 주문을 모의체결 큐로 전송',
    description: '위험관리를 통과한 주문만 모의체결 큐에 등록합니다. 주문 접수 이후의 첫 체결 가능 데이터만 사용합니다.',
    color: '#1F2937',
    icon: 'arrow',
    inputs: [{ id: 'approved', label: '승인 주문', type: 'ApprovedOrder' }],
    outputs: [],
    parameterSchema: [
      { key: 'orderType', label: '주문 방식', type: 'select', required: true, primary: true, options: [{ label: '시장가', value: 'market' }, { label: '지정가', value: 'limit' }] },
      { key: 'session', label: '거래 시간', type: 'select', required: true, options: [{ label: '정규장만', value: 'regular' }, { label: '사용자 일정 블록', value: 'schedule' }] },
    ],
    parameters: { orderType: 'market', session: 'regular' },
  }),
  node({
    blockId: 'decision-record',
    label: '결정 기록',
    stage: '관찰·기록',
    detail: '판단 근거와 입력값 저장',
    description: '실행 흐름에 영향을 주지 않고 선택한 지표와 주문 판단 근거를 감사 기록으로 남깁니다.',
    color: '#0E7490',
    icon: 'eye',
    inputs: [{ id: 'metric', label: '관찰 값', type: 'Metric', optional: true, observation: true }],
    outputs: [],
    parameterSchema: [{ key: 'scope', label: '기록 범위', type: 'select', required: true, primary: true, options: [{ label: '모든 판단', value: 'all' }, { label: '상태 변화만', value: 'changes' }] }],
    parameters: { scope: 'all' },
  }),
  node({
    blockId: 'zscore',
    label: '롤링 z-score',
    stage: '특징·지표',
    detail: '페어 스프레드 진단값',
    description: '두 자산의 스프레드를 롤링 평균과 표준편차로 표준화합니다. 진단값이며 투자 추천 신호가 아닙니다.',
    color: '#6D28D9',
    icon: 'function',
    inputs: [{ id: 'pair', label: '두 자산', type: 'AssetPair' }],
    outputs: [{ id: 'scalar', label: 'z-score', type: 'Scalar' }],
    parameterSchema: [{ key: 'lookback', label: '롤링 기간', type: 'number', required: true, primary: true, min: 20, max: 240 }],
    parameters: { lookback: '' },
    formula: 'z = (spread - μ) / σ',
    dataCapability: 'daily_history',
  }),
  node({
    blockId: 'short-filter',
    label: '공매도 가능 필터',
    stage: '위험관리',
    detail: '현재 공매도 가능 상태 확인',
    description: '실시간 공급자가 제공한 공매도 가능 상태가 없으면 신규 숏 주문을 거부합니다.',
    color: '#B91C1C',
    icon: 'shield',
    inputs: [{ id: 'intent', label: '주문 의도', type: 'OrderIntent' }],
    outputs: [{ id: 'approved', label: '승인 주문', type: 'ApprovedOrder' }],
    parameterSchema: [],
    parameters: {},
    dataCapability: 'short_availability_live',
    locked: true,
    lockReason: '현재 데모 환경에는 실시간 공매도 가능 데이터가 없습니다.',
  }),
  node({
    blockId: 'twap',
    label: 'TWAP 분할 실행',
    stage: '주문 실행',
    detail: '주문을 시간 간격으로 분할',
    description: '승인된 주문을 사용자가 정한 횟수와 시간으로 나누어 모의 실행합니다.',
    color: '#1F2937',
    icon: 'arrow',
    inputs: [{ id: 'approved', label: '승인 주문', type: 'ApprovedOrder' }],
    outputs: [],
    parameterSchema: [
      { key: 'slices', label: '분할 횟수', type: 'number', required: true, primary: true, min: 2, max: 20 },
      { key: 'minutes', label: '실행 시간', type: 'number', suffix: '분', required: true, primary: true, min: 5, max: 180 },
    ],
    parameters: { slices: '', minutes: '' },
  }),
];

export const initialBots: Bot[] = [
  {
    id: 1,
    name: '데이터 확인 필요 봇',
    state: 'attention',
    strategy: '직접 구성 전략',
    version: 'v3',
    symbols: ['AAPL'],
    openOrders: 1,
    positionCount: 1,
    nextCheck: '확인 후 재개',
    issue: '가격 데이터 갱신이 7분 지연됐습니다.',
    activity: ['22:41 데이터 지연 감지', '22:40 신규 주문 생성 중단', '22:36 지정가 주문 제출'],
  },
  {
    id: 2,
    name: '학습용 라이브 모의 봇',
    state: 'running',
    strategy: '단일 조건 구조',
    version: 'v1',
    symbols: ['MSFT'],
    openOrders: 2,
    positionCount: 1,
    nextCheck: '3분 18초 후',
    activity: ['22:42 조건 평가: 미충족', '22:37 기존 주문 유지', '22:32 데이터 정상 수신'],
  },
  {
    id: 3,
    name: '구조 실험 봇',
    state: 'paused',
    strategy: '복수 조건 구조',
    version: 'v2',
    symbols: ['NVDA'],
    openOrders: 1,
    positionCount: 0,
    nextCheck: '일시정지 중',
    activity: ['21:15 사용자 일시정지', '21:15 열린 주문 1건 유지', '21:10 조건 평가 완료'],
  },
];

export const initialRooms: Room[] = [
  { id: 1, name: '여름 학습 대회', owner: 'I2S 공식', status: '모집 중', period: '08.01 - 08.31', members: 28 },
  { id: 2, name: 'B205 전략 실험실', owner: '민경철', status: '진행 중', period: '07.15 - 08.15', members: 7, joined: true },
  { id: 3, name: '리스크 기록 스터디', owner: 'RM', status: '예정', period: '08.10 - 09.10', members: 4, mine: true },
];

export const stateLabel: Record<BotState, string> = {
  running: '실행 중',
  paused: '일시정지',
  stopped: '중단',
  attention: '조치 필요',
  ended: '운영 종료',
};
